export const countryCodes = [
  { code: '+1', country: 'United States', currency: 'USD' },
  { code: '+1', country: 'Canada', currency: 'CAD' },
  { code: '+7', country: 'Russia', currency: 'RUB' },
  { code: '+7', country: 'Kazakhstan', currency: 'KZT' },
  { code: '+20', country: 'Egypt', currency: 'EGP' },
  { code: '+27', country: 'South Africa', currency: 'ZAR' },
  { code: '+30', country: 'Greece', currency: 'EUR' },
  { code: '+31', country: 'Netherlands', currency: 'EUR' },
  { code: '+32', country: 'Belgium', currency: 'EUR' },
  { code: '+33', country: 'France', currency: 'EUR' },
  { code: '+34', country: 'Spain', currency: 'EUR' },
  { code: '+36', country: 'Hungary', currency: 'HUF' },
  { code: '+39', country: 'Italy', currency: 'EUR' },
  { code: '+40', country: 'Romania', currency: 'RON' },
  { code: '+41', country: 'Switzerland', currency: 'CHF' },
  { code: '+43', country: 'Austria', currency: 'EUR' },
  { code: '+44', country: 'United Kingdom', currency: 'GBP' },
  { code: '+45', country: 'Denmark', currency: 'DKK' },
  { code: '+46', country: 'Sweden', currency: 'SEK' },
  { code: '+47', country: 'Norway', currency: 'NOK' },
  { code: '+48', country: 'Poland', currency: 'PLN' },
  { code: '+49', country: 'Germany', currency: 'EUR' },
  { code: '+51', country: 'Peru', currency: 'PEN' },
  { code: '+52', country: 'Mexico', currency: 'MXN' },
  { code: '+53', country: 'Cuba', currency: 'CUP' },
  { code: '+54', country: 'Argentina', currency: 'ARS' },
  { code: '+55', country: 'Brazil', currency: 'BRL' },
  { code: '+56', country: 'Chile', currency: 'CLP' },
  { code: '+57', country: 'Colombia', currency: 'COP' },
  { code: '+58', country: 'Venezuela', currency: 'VED' },
  { code: '+60', country: 'Malaysia', currency: 'MYR' },
  { code: '+61', country: 'Australia', currency: 'AUD' },
  { code: '+62', country: 'Indonesia', currency: 'IDR' },
  { code: '+63', country: 'Philippines', currency: 'PHP' },
  { code: '+64', country: 'New Zealand', currency: 'NZD' },
  { code: '+65', country: 'Singapore', currency: 'SGD' },
  { code: '+66', country: 'Thailand', currency: 'THB' },
  { code: '+81', country: 'Japan', currency: 'JPY' },
  { code: '+82', country: 'South Korea', currency: 'KRW' },
  { code: '+84', country: 'Vietnam', currency: 'VND' },
  { code: '+86', country: 'China', currency: 'CNY' },
  { code: '+90', country: 'Turkey', currency: 'TRY' },
  { code: '+91', country: 'India', currency: 'INR' },
  { code: '+92', country: 'Pakistan', currency: 'PKR' },
  { code: '+93', country: 'Afghanistan', currency: 'AFN' },
  { code: '+94', country: 'Sri Lanka', currency: 'LKR' },
  { code: '+95', country: 'Myanmar', currency: 'MMK' },
  { code: '+98', country: 'Iran', currency: 'IRR' },
  { code: '+212', country: 'Morocco', currency: 'MAD' },
  { code: '+213', country: 'Algeria', currency: 'DZD' },
  { code: '+216', country: 'Tunisia', currency: 'TND' },
  { code: '+218', country: 'Libya', currency: 'LYD' },
  { code: '+220', country: 'Gambia', currency: 'GMD' },
  { code: '+221', country: 'Senegal', currency: 'XOF' },
  { code: '+222', country: 'Mauritania', currency: 'MRU' },
  { code: '+223', country: 'Mali', currency: 'XOF' },
  { code: '+224', country: 'Guinea', currency: 'GNF' },
  { code: '+225', country: 'Ivory Coast', currency: 'XOF' },
  { code: '+226', country: 'Burkina Faso', currency: 'XOF' },
  { code: '+227', country: 'Niger', currency: 'XOF' },
  { code: '+228', country: 'Togo', currency: 'XOF' },
  { code: '+229', country: 'Benin', currency: 'XOF' },
  { code: '+230', country: 'Mauritius', currency: 'MUR' },
  { code: '+231', country: 'Liberia', currency: 'LRD' },
  { code: '+232', country: 'Sierra Leone', currency: 'SLE' },
  { code: '+233', country: 'Ghana', currency: 'GHS' },
  { code: '+234', country: 'Nigeria', currency: 'NGN' },
  { code: '+235', country: 'Chad', currency: 'XAF' },
  { code: '+236', country: 'Central African Republic', currency: 'XAF' },
  { code: '+237', country: 'Cameroon', currency: 'XAF' },
  { code: '+238', country: 'Cape Verde', currency: 'CVE' },
  { code: '+239', country: 'São Tomé and Príncipe', currency: 'STN' },
  { code: '+240', country: 'Equatorial Guinea', currency: 'XAF' },
  { code: '+241', country: 'Gabon', currency: 'XAF' },
  { code: '+242', country: 'Republic of Congo', currency: 'XAF' },
  { code: '+243', country: 'Democratic Republic of Congo', currency: 'CDF' },
  { code: '+244', country: 'Angola', currency: 'AOA' },
  { code: '+245', country: 'Guinea-Bissau', currency: 'XOF' },
  { code: '+246', country: 'British Indian Ocean Territory', currency: 'USD' },
  { code: '+248', country: 'Seychelles', currency: 'SCR' },
  { code: '+249', country: 'Sudan', currency: 'SDG' },
  { code: '+250', country: 'Rwanda', currency: 'RWF' },
  { code: '+251', country: 'Ethiopia', currency: 'ETB' },
  { code: '+252', country: 'Somalia', currency: 'SOS' },
  { code: '+253', country: 'Djibouti', currency: 'DJF' },
  { code: '+254', country: 'Kenya', currency: 'KES' },
  { code: '+255', country: 'Tanzania', currency: 'TZS' },
  { code: '+256', country: 'Uganda', currency: 'UGX' },
  { code: '+257', country: 'Burundi', currency: 'BIF' },
  { code: '+258', country: 'Mozambique', currency: 'MZN' },
  { code: '+260', country: 'Zambia', currency: 'ZMW' },
  { code: '+261', country: 'Madagascar', currency: 'MGA' },
  { code: '+262', country: 'Mayotte', currency: 'EUR' },
  { code: '+263', country: 'Zimbabwe', currency: 'ZWL' },
  { code: '+264', country: 'Namibia', currency: 'NAD' },
  { code: '+265', country: 'Malawi', currency: 'MWK' },
  { code: '+266', country: 'Lesotho', currency: 'LSL' },
  { code: '+267', country: 'Botswana', currency: 'BWP' },
  { code: '+268', country: 'Eswatini', currency: 'SZL' },
  { code: '+269', country: 'Comoros', currency: 'KMF' },
  { code: '+290', country: 'Saint Helena', currency: 'SHP' },
  { code: '+291', country: 'Eritrea', currency: 'ERN' },
  { code: '+297', country: 'Aruba', currency: 'AWG' },
  { code: '+298', country: 'Faroe Islands', currency: 'DKK' },
  { code: '+299', country: 'Greenland', currency: 'DKK' },
  { code: '+350', country: 'Gibraltar', currency: 'GIP' },
  { code: '+351', country: 'Portugal', currency: 'EUR' },
  { code: '+352', country: 'Luxembourg', currency: 'EUR' },
  { code: '+353', country: 'Ireland', currency: 'EUR' },
  { code: '+354', country: 'Iceland', currency: 'ISK' },
  { code: '+355', country: 'Albania', currency: 'ALL' },
  { code: '+356', country: 'Malta', currency: 'EUR' },
  { code: '+357', country: 'Cyprus', currency: 'EUR' },
  { code: '+358', country: 'Finland', currency: 'EUR' },
  { code: '+359', country: 'Bulgaria', currency: 'BGN' },
  { code: '+370', country: 'Lithuania', currency: 'EUR' },
  { code: '+371', country: 'Latvia', currency: 'EUR' },
  { code: '+372', country: 'Estonia', currency: 'EUR' },
  { code: '+373', country: 'Moldova', currency: 'MDL' },
  { code: '+374', country: 'Armenia', currency: 'AMD' },
  { code: '+375', country: 'Belarus', currency: 'BYN' },
  { code: '+376', country: 'Andorra', currency: 'EUR' },
  { code: '+377', country: 'Monaco', currency: 'EUR' },
  { code: '+378', country: 'San Marino', currency: 'EUR' },
  { code: '+380', country: 'Ukraine', currency: 'UAH' },
  { code: '+381', country: 'Serbia', currency: 'RSD' },
  { code: '+382', country: 'Montenegro', currency: 'EUR' },
  { code: '+383', country: 'Kosovo', currency: 'EUR' },
  { code: '+385', country: 'Croatia', currency: 'EUR' },
  { code: '+386', country: 'Slovenia', currency: 'EUR' },
  { code: '+387', country: 'Bosnia and Herzegovina', currency: 'BAM' },
  { code: '+389', country: 'North Macedonia', currency: 'MKD' },
  { code: '+420', country: 'Czech Republic', currency: 'CZK' },
  { code: '+421', country: 'Slovakia', currency: 'EUR' },
  { code: '+423', country: 'Liechtenstein', currency: 'CHF' },
  { code: '+500', country: 'Falkland Islands', currency: 'FKP' },
  { code: '+501', country: 'Belize', currency: 'BZD' },
  { code: '+502', country: 'Guatemala', currency: 'GTQ' },
  { code: '+503', country: 'El Salvador', currency: 'USD' },
  { code: '+504', country: 'Honduras', currency: 'HNL' },
  { code: '+505', country: 'Nicaragua', currency: 'NIO' },
  { code: '+506', country: 'Costa Rica', currency: 'CRC' },
  { code: '+507', country: 'Panama', currency: 'PAB' },
  { code: '+508', country: 'Saint Pierre and Miquelon', currency: 'EUR' },
  { code: '+509', country: 'Haiti', currency: 'HTG' },
  { code: '+590', country: 'Guadeloupe', currency: 'EUR' },
  { code: '+591', country: 'Bolivia', currency: 'BOB' },
  { code: '+592', country: 'Guyana', currency: 'GYD' },
  { code: '+593', country: 'Ecuador', currency: 'USD' },
  { code: '+594', country: 'French Guiana', currency: 'EUR' },
  { code: '+595', country: 'Paraguay', currency: 'PYG' },
  { code: '+596', country: 'Martinique', currency: 'EUR' },
  { code: '+597', country: 'Suriname', currency: 'SRD' },
  { code: '+598', country: 'Uruguay', currency: 'UYU' },
  { code: '+599', country: 'Caribbean Netherlands', currency: 'USD' },
  { code: '+670', country: 'East Timor', currency: 'USD' },
  { code: '+672', country: 'Norfolk Island', currency: 'AUD' },
  { code: '+673', country: 'Brunei', currency: 'BND' },
  { code: '+674', country: 'Nauru', currency: 'AUD' },
  { code: '+675', country: 'Papua New Guinea', currency: 'PGK' },
  { code: '+676', country: 'Tonga', currency: 'TOP' },
  { code: '+677', country: 'Solomon Islands', currency: 'SBD' },
  { code: '+678', country: 'Vanuatu', currency: 'VUV' },
  { code: '+679', country: 'Fiji', currency: 'FJD' },
  { code: '+680', country: 'Palau', currency: 'USD' },
  { code: '+681', country: 'Wallis and Futuna', currency: 'XPF' },
  { code: '+682', country: 'Cook Islands', currency: 'NZD' },
  { code: '+683', country: 'Niue', currency: 'NZD' },
  { code: '+684', country: 'American Samoa', currency: 'USD' },
  { code: '+685', country: 'Samoa', currency: 'WST' },
  { code: '+686', country: 'Kiribati', currency: 'AUD' },
  { code: '+687', country: 'New Caledonia', currency: 'XPF' },
  { code: '+688', country: 'Tuvalu', currency: 'AUD' },
  { code: '+689', country: 'French Polynesia', currency: 'XPF' },
  { code: '+690', country: 'Tokelau', currency: 'NZD' },
  { code: '+691', country: 'Micronesia', currency: 'USD' },
  { code: '+692', country: 'Marshall Islands', currency: 'USD' },
  { code: '+850', country: 'North Korea', currency: 'KPW' },
  { code: '+852', country: 'Hong Kong', currency: 'HKD' },
  { code: '+853', country: 'Macau', currency: 'MOP' },
  { code: '+855', country: 'Cambodia', currency: 'KHR' },
  { code: '+856', country: 'Laos', currency: 'LAK' },
  { code: '+880', country: 'Bangladesh', currency: 'BDT' },
  { code: '+886', country: 'Taiwan', currency: 'TWD' },
  { code: '+960', country: 'Maldives', currency: 'MVR' },
  { code: '+961', country: 'Lebanon', currency: 'LBP' },
  { code: '+962', country: 'Jordan', currency: 'JOD' },
  { code: '+963', country: 'Syria', currency: 'SYP' },
  { code: '+964', country: 'Iraq', currency: 'IQD' },
  { code: '+965', country: 'Kuwait', currency: 'KWD' },
  { code: '+966', country: 'Saudi Arabia', currency: 'SAR' },
  { code: '+967', country: 'Yemen', currency: 'YER' },
  { code: '+968', country: 'Oman', currency: 'OMR' },
  { code: '+970', country: 'Palestine', currency: 'ILS' },
  { code: '+971', country: 'United Arab Emirates', currency: 'AED' },
  { code: '+972', country: 'Israel', currency: 'ILS' },
  { code: '+973', country: 'Bahrain', currency: 'BHD' },
  { code: '+974', country: 'Qatar', currency: 'QAR' },
  { code: '+975', country: 'Bhutan', currency: 'BTN' },
  { code: '+976', country: 'Mongolia', currency: 'MNT' },
  { code: '+977', country: 'Nepal', currency: 'NPR' },
  { code: '+992', country: 'Tajikistan', currency: 'TJS' },
  { code: '+993', country: 'Turkmenistan', currency: 'TMT' },
  { code: '+994', country: 'Azerbaijan', currency: 'AZN' },
  { code: '+995', country: 'Georgia', currency: 'GEL' },
  { code: '+996', country: 'Kyrgyzstan', currency: 'KGS' },
  { code: '+998', country: 'Uzbekistan', currency: 'UZS' }
];